# Configurations
title:            Dukhyun Gitbook
longtitle:        Dukhyun Gitbook
author:           Dukhyun, Lee
email:            ideook@gmail.com
description: >
  Build Jekyll site with the GitBook style.

version:          1.0
gitbook_version:  3.2.3

url:              'https://haeahn-dukhyun.github.io'
baseurl:          '/'
rss:              RSS

toc:
  enabled: true
  h_min: 1
  h_max: 3

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:year/:month/:title

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-archives
